version: '3.6'

services:
  srvdb:
    image: postgres
    container_name: srvdb
    hostname: srvdb
    environment:
      POSTGRES_USER: consultas
      POSTGRES_DB: consultas
      POSTGRES_PASSWORD: QueryConSql.pwd
    ports:
      - "5432:5432"
    networks:
      - demo_kcs_net

  srvwildfly:
    image: paulguzhnay/srv-apilayer:latest
    container_name: srvwildfly
    hostname: srvwildfly
    ports:
      - "8080:8080"
      - "9990:9990"
    depends_on:
      - srvdb
    networks:
      - demo_kcs_net

  api_service:
    image: paulguzhnay/srv-apilayer:latest
    container_name: api_service
    hostname: api_service
    ports:
      - "8082:8080"  # Mapea el puerto 8080 del contenedor al puerto 8082 del host
    depends_on:
      - srvdb
    networks:
      - demo_kcs_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: info@jtux.ec
      PGADMIN_DEFAULT_PASSWORD: clave
    ports:
      - "5050:80"
    depends_on:
      - srvdb
    networks:
      - demo_kcs_net

  nginx:
    image: nginx:latest
    container_name: nginx
    hostname: nginx
    ports:
      - "8081:8081"  # Expone el puerto 8081 en el host para Nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Monta tu archivo de configuración personalizado
    depends_on:
      - srvwildfly
      - api_service
    networks:
      - demo_kcs_net

networks:
  demo_kcs_net:
    driver: bridge
